services:
  bff:
    build:
      context: .
      dockerfile: Dockerfile.bff
    ports:
      - "3001:3001"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://0.0.0.0:3001"
  
  identity:
    build:
      context: .
      dockerfile: Dockerfile.identity
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://0.0.0.0:5001"

  message:
    build:
      context: .
      dockerfile: Dockerfile.message
    ports:
      - "6001:6001"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://0.0.0.0:6001"
